"""empty message

Revision ID: 2854af595777
Revises: 368f2ce6eb0e
Create Date: 2019-06-11 12:53:35.311403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2854af595777'
down_revision = '368f2ce6eb0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ffmpeg_params_image', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_instance', schema=None) as batch_op:
        batch_op.drop_column('ffmpeg_params_image')

    # ### end Alembic commands ###
