"""empty message

Revision ID: 33eca2de08db
Revises: 9692bc4ca91f
Create Date: 2019-06-10 16:45:39.107002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33eca2de08db'
down_revision = '9692bc4ca91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_instance', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
