"""empty message

Revision ID: 3751e474b462
Revises: fcdb2e31edf6
Create Date: 2019-06-10 17:52:07.769667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3751e474b462'
down_revision = 'fcdb2e31edf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ffmpeg_params', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_instance', schema=None) as batch_op:
        batch_op.drop_column('ffmpeg_params')

    # ### end Alembic commands ###
