"""empty message

Revision ID: 782fa2a525ac
Revises: 3751e474b462
Create Date: 2019-06-11 02:01:26.614905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782fa2a525ac'
down_revision = '3751e474b462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_content', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
