"""empty message

Revision ID: 9692bc4ca91f
Revises: 
Create Date: 2019-06-10 15:30:20.393056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9692bc4ca91f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_role_name'), ['name'])

    with op.batch_alter_table('uploaded_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_instance', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_uploaded_content_data_instance_data_instance'), 'data_instance', ['data_instance'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_foreign_key(batch_op.f('fk_user_role_role'), 'role', ['role'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_role_role'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.drop_column('role')

    with op.batch_alter_table('uploaded_content', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_uploaded_content_data_instance_data_instance'), type_='foreignkey')
        batch_op.drop_column('data_instance')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_role_name'), type_='unique')

    # ### end Alembic commands ###
