"""empty message

Revision ID: 9fa43a1304e0
Revises: e759851ef7f4
Create Date: 2019-06-10 04:38:20.607857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa43a1304e0'
down_revision = 'e759851ef7f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_content', schema=None) as batch_op:
        batch_op.drop_column('file_type')

    # ### end Alembic commands ###
