"""empty message

Revision ID: bc3532c89562
Revises: 2854af595777
Create Date: 2019-06-11 14:12:15.902518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3532c89562'
down_revision = '2854af595777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_content', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
