"""empty message

Revision ID: fcdb2e31edf6
Revises: 33eca2de08db
Create Date: 2019-06-10 17:05:57.649709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdb2e31edf6'
down_revision = '33eca2de08db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data_instances',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data_instance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_instance_id'], ['data_instance.id'], name=op.f('fk_user_data_instances_data_instance_id_data_instance')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_data_instances_user_id_user'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_data_instances')
    # ### end Alembic commands ###
